services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/DigiMeet
      FLASK_APP: server.py
      FLASK_ENV: development
    volumes:
      - .:/app

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./assets:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_DATABASE: DigiMeet
      
  
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
